networks:
  amr_mesh:
    driver: bridge

services:
  warehouse_sim:
    build:
      context: .
      dockerfile: Dockerfile.warehouse
    container_name: warehouse_sim
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5555:5555"
    networks:
      - amr_mesh

  amr_1:
    build:
      context: .
      dockerfile: Dockerfile.amr
    container_name: amr_1
    depends_on:
      - warehouse_sim
    environment:
      - PYTHONUNBUFFERED=1
      - WAREHOUSE_ADDR=tcp://warehouse_sim:5555
    command: python amr/amr_node.py amr_1 1 14 28 14 6001 "tcp://amr_2:6002,tcp://amr_3:6003"
    networks:
      - amr_mesh

  amr_2:
    build:
      context: .
      dockerfile: Dockerfile.amr
    container_name: amr_2
    depends_on:
      - warehouse_sim
    environment:
      - PYTHONUNBUFFERED=1
      - WAREHOUSE_ADDR=tcp://warehouse_sim:5555
    command: python amr/amr_node.py amr_2 14 1 14 28 6002 "tcp://amr_1:6001,tcp://amr_3:6003"
    networks:
      - amr_mesh

  amr_3:
    build:
      context: .
      dockerfile: Dockerfile.amr
    container_name: amr_3
    depends_on:
      - warehouse_sim
    environment:
      - PYTHONUNBUFFERED=1
      - WAREHOUSE_ADDR=tcp://warehouse_sim:5555
    command: python amr/amr_node.py amr_3 28 14 1 14 6003 "tcp://amr_1:6001,tcp://amr_2:6002"
    networks:
      - amr_mesh
