FROM python:3.10-slim

WORKDIR /app

ENV PYTHONPATH=/app

RUN pip install --no-cache-dir pyzmq numpy torch --extra-index-url https://download.pytorch.org/whl/cpu

COPY amr/ /app/amr/
COPY core/ /app/core/
COPY marl/ /app/marl/
COPY mappo_actor.pt /app/mappo_actor.pt

CMD ["python"]
