FROM python:3.10-slim

WORKDIR /app

ENV PYTHONPATH=/app

RUN pip install pyzmq numpy

COPY core/ /app/core/
COPY simulation/ /app/simulation/

EXPOSE 5555

CMD ["python", "simulation/warehouse_server.py"]
